<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MarcasComerciaisSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('marcas_comerciais')->insert([
            ['nome' => 'A  DEFINIR'],
            ['nome' => 'ACORDE'],
            ['nome' => 'ACORDE TABACO'],
            ['nome' => 'ALCANCE'],
            ['nome' => 'AMAIZ'],
            ['nome' => 'APPLIKER'],
            ['nome' => 'BEAUVEBIO (Beauveria bassiana)'],
            ['nome' => 'BIODRYER BLACK DIAMOND 50'],
            ['nome' => 'BIODRYER SILVER'],
            ['nome' => 'BIOFIX FORCE BLACK'],
            ['nome' => 'BIOFIX FORCE BLACK SHINY'],
            ['nome' => 'BIOFIX FORCE BLUE'],
            ['nome' => 'BIOFIX FORCE BLUE SHINY'],
            ['nome' => 'BIOFIX FORCE CLEAN'],
            ['nome' => 'BIOFIX FORCE CLEAN SHINY'],
            ['nome' => 'BIOFIX FORCE GREEN'],
            ['nome' => 'BIOFIX FORCE GREEN SHINY'],
            ['nome' => 'BIOFIX FORCE RED'],
            ['nome' => 'BIOFIX FORCE RED SHINY'],
            ['nome' => 'BIOFORCE RED SHINY CEREALIS'],
            ['nome' => 'BIOTINA'],
            ['nome' => 'BOROGÊNIO'],
            ['nome' => 'BOX CROPBIO PHOS'],
            ['nome' => 'BRADDOCK K'],
            ['nome' => 'BRADDOCK WG'],
            ['nome' => 'CAB 8:2'],
            ['nome' => 'CARTAGO OU '],
            ['nome' => 'CHOLLA (B. aryabhattai)'],
            ['nome' => 'CLOMASTER'],
            ['nome' => 'CLORPIRIFÓS FERSOL'],
            ['nome' => 'CLORPIRIFÓS GHARDA'],
            ['nome' => 'COMO FERT'],
            ['nome' => 'COMONI'],
            ['nome' => 'COMOZin'],
            ['nome' => 'COMPAT'],
            ['nome' => 'CONTROL T'],
            ['nome' => 'CROP 30 '],
            ['nome' => 'CROP 30 BR'],
            ['nome' => 'CROP ACTIVE K20 '],
            ['nome' => 'CROP ACTIVE Mn'],
            ['nome' => 'CROP CMA GRAM'],
            ['nome' => 'CROP CMA Ni'],
            ['nome' => 'CROP DEFENDER'],
            ['nome' => 'CROP OIL'],
            ['nome' => 'CROP POTASSIUM ULTRA'],
            ['nome' => 'CROPBIO AZOS'],
            ['nome' => 'CROPBIO SOJA 7x10ˆ9'],
            ['nome' => 'CROPBIO TURFA'],
            ['nome' => 'CUPROSO'],
            ['nome' => 'CUPROZIN ULTRA '],
            ['nome' => 'CUTLASS'],
            ['nome' => 'DAGA'],
            ['nome' => 'DERRETE'],
            ['nome' => 'DIAFENTIUROM 500'],
            ['nome' => 'DOTTE'],
            ['nome' => 'ELEGANCE 500 SC'],
            ['nome' => 'ENDURANCE'],
            ['nome' => 'ETIPROLE 200'],
            ['nome' => 'FECYDE'],
            ['nome' => 'FIPRONIL GHARDA 800 WG'],
            ['nome' => 'FLUTOX '],
            ['nome' => 'FLUXUS'],
            ['nome' => 'FULLGUARD'],
            ['nome' => 'GARANHÃO'],
            ['nome' => 'IMIDACLOPRID HAILER 600 FS'],
            ['nome' => 'INSTAL '],
            ['nome' => 'INTENSE'],
            ['nome' => 'KIT GUARDIAN'],
            ['nome' => 'KIT TRABUCO '],
            ['nome' => 'LUFENURON 50'],
            ['nome' => 'MANGANÊS 150'],
            ['nome' => 'MASTERTRIONA'],
            ['nome' => 'MAX MOL'],
            ['nome' => 'METOMIL 215'],
            ['nome' => 'MIRA 900 WG'],
            ['nome' => 'MISTER'],
            ['nome' => 'MOL 2,4 D'],
            ['nome' => 'N FIX'],
            ['nome' => 'NEMATHA (B. amyloliquefaciens)'],
            ['nome' => 'NITROMAG'],
            ['nome' => 'OPRESSOR'],
            ['nome' => 'OPTIBEX'],
            ['nome' => 'OUT ADJ'],
            ['nome' => 'PIRADO / ADVER'],
            ['nome' => 'PRATICO'],
            ['nome' => 'PREVENT GOLD'],
            ['nome' => 'PROTANK'],
            ['nome' => 'READY FIX'],
            ['nome' => 'REMOUVER'],
            ['nome' => 'RYFLI'],
            ['nome' => 'SIDRAK'],
            ['nome' => 'SOLLUS MOL'],
            ['nome' => 'SOLLUS MOL ULTRA'],
            ['nome' => 'STALLION'],
            ['nome' => 'STALLION ULTRA'],
            ['nome' => 'STIVA'],
            ['nome' => 'SULBAN'],
            ['nome' => 'SURRATEIRO'],
            ['nome' => 'TALLADEGA'],
            ['nome' => 'TEBURAZ'],
            ['nome' => 'TERPEN'],
            ['nome' => 'TRABUCO '],
            ['nome' => 'TREMOR'],
            ['nome' => 'TRICHOKING (T. asperellum)'],
            ['nome' => 'TRIPLO N '],
            ['nome' => 'ULTRA FIX'],
            ['nome' => 'ULTRA FIX AIR'],
            ['nome' => 'USER 430 BR'],
            ['nome' => 'VALENTE BR'],
            ['nome' => 'VENIA BR'],
            ['nome' => 'VIVANTHA'],
            ['nome' => 'ZAPRET'],
            ['nome' => 'ZETA'],
            ['nome' => 'ZINCOGÊNIO'],
            ['nome' => 'ZOM'],
        ]);
    }
}
